# Generated by Django 5.0.1 on 2024-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('user', models.TextField()),
                ('date_of_buying', models.IntegerField()),
                ('payment_status', models.TextField()),
                ('order_status', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('product', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.TextField()),
                ('quantity', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='')),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.IntegerField()),
                ('location', models.TextField()),
            ],
        ),
    ]
