# Generated by Django 5.0.7 on 2024-08-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='buy',
            name='date_of_buying',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
    ]
