# Generated by Django 5.0.7 on 2024-08-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_buy_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.IntegerField()),
                ('root', models.TextField()),
            ],
        ),
    ]
