# Generated by Django 5.0.7 on 2024-08-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delreg',
            old_name='root',
            new_name='delroot',
        ),
    ]
