# Generated by Django 5.0.1 on 2024-08-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_root_delreg_delroot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delreg',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='delreg',
            old_name='delroot',
            new_name='rout',
        ),
        migrations.AddField(
            model_name='buy',
            name='del_boy',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='delpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.TextField(null=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delreg')),
            ],
        ),
    ]
