# Generated by Django 5.0.1 on 2024-12-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_buy_del_boy_remove_buy_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delreg',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(),
        ),
    ]
